name: telewapp
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

flutter:
  plugin:
    platforms:
      web:

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7
  meta: 1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.0
